{% extends "layout.swig" %}

{% block site-title %}TaskList{% endblock %}

{% block body %}
  <div>
    <h1>AzureCamp Resources</h1>
    <div> 
      <p><strong>Nodejs app</strong> <a href="https://github.com/arifsetiawan/tasklist" target="_blank">https://github.com/arifsetiawan/tasklist</a></p>

      <p><strong>Working with Azure CLI</strong> <a href="https://gist.github.com/arifsetiawan/afcf9adeb9922066f81f" target="_blank">https://gist.github.com/arifsetiawan/afcf9adeb9922066f81f</a></p>
      
      <p><strong>Deploy Node.js app</strong> <a href="https://gist.github.com/arifsetiawan/5f7e2d0a69306fbbd28f" target="_blank">https://gist.github.com/arifsetiawan/5f7e2d0a69306fbbd28f</a></p>
      
      <p><strong>Android AsyncTask data</strong> <a href="https://gist.github.com/arifsetiawan/9f34dbb9d859ec109de1" target="_blank">https://gist.github.com/arifsetiawan/9f34dbb9d859ec109de1</a></p>

      <p><strong>Better console for Windows</strong> <a href="http://sourceforge.net/projects/console/" target="_blank">http://sourceforge.net/projects/console/</a> or <a href="https://github.com/cbucher/console" target="_blank">https://github.com/cbucher/console</a></p>

      <p><strong>Azure documentation</strong></p>
      <ul>
        <li><a href="http://azure.microsoft.com/en-us/documentation/articles/command-line-tools/" target="_blank">http://azure.microsoft.com/en-us/documentation/articles/command-line-tools/</a></li>
        <li><a href="http://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-use-table-storage-web-site/" target="_blank">http://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-use-table-storage-web-site/</a></li>
        <li><a href="http://azure.microsoft.com/en-us/documentation/articles/mobile-services-android-how-to-use-client-library/" target="_blank">http://azure.microsoft.com/en-us/documentation/articles/mobile-services-android-how-to-use-client-library/</a></li>
      </ul>

      
    </div>
  </div>
{% endblock %}

